name: Build/release Electron app

on:
  push:
    tags:
      - 'v*.*.*'
      - 'beta'
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            release/**/*.exe
            release/**/*.zip
            release/**/*.dmg
            release/**/*.snap
            release/**/*.deb
            release/**/*.rpm
            release/**/*.tar.gz
            release/**/*.yml
            release/**/*.blockmap
            release/**/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}